name: Build, Publish & Deploy

on:
  push:
    branches: [ main ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image to GHCR
        uses: docker/build-push-action@v5
        with:
          context: ./rakotee-backend
          file: ./rakotee-backend/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/rakotee-backend:latest
            ghcr.io/${{ github.repository_owner }}/rakotee-backend:${{ github.sha }}
          target: final

      - name: Trigger Render deploy (optional)
        if: ${{ secrets.RENDER_API_KEY != '' }}
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
        run: |
          echo "Triggering Render deploy for service $SERVICE_ID"
          curl -X POST https://api.render.com/v1/services/$SERVICE_ID/deploys \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer $RENDER_API_KEY" \
            -d '{"clearCache":true}'
